In [6]:
import pandas as pd
import numpy as np
test = pd.read_csv("/home/sunshuo/qml/TradeMaster-1/data/data/dj30/train.csv",index_col=0)
test.index.unique().tolist().sort()

<function list.sort(*, key=None, reverse=False)>

In [7]:
import torch
from torch import nn
m = nn.Softmax(dim=1)
input = torch.randn(2, 3)
output = m(input)

In [8]:
output

tensor([[0.1535, 0.6031, 0.2435],
        [0.9029, 0.0605, 0.0365]])

In [9]:
torch.cat([torch.randn(1),torch.randn(1),torch.randn(1),torch.randn(1),torch.randn(1)])

tensor([ 0.7530,  0.1940, -0.0454,  0.6175,  0.6000])

In [11]:
m(torch.cat([torch.randn(1),torch.randn(1),torch.randn(1),torch.randn(1),torch.randn(1)]).unsqueeze(0))

tensor([[0.0827, 0.1401, 0.2361, 0.0792, 0.4619]])

In [1]:
[1,2,3,4,5,6,777,8].index(777)

6

In [2]:
import torch 
from torch.distributions import Normal
normal = Normal(0, 2)
result = normal.sample()


/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
result

tensor(-1.1969)

In [3]:
result<=0

tensor(True)

In [1]:
import torch
torch.tensor([torch.tensor(1)])

/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([1])

In [4]:
normal = Normal(1, 2)
result = normal.sample()


In [5]:
normal.log_prob(result)

tensor(-2.2420)

In [6]:
import torch 
torch.tensor(1)*torch.tensor(2)

tensor(2)

In [1]:
import torch
torch.ones(29)*1/29

/home/sunshuo/miniconda3/envs/TradeMaster/lib/python3.7/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345, 0.0345,
        0.0345, 0.0345])

In [5]:
def make_market_information(df, technical_indicator):
    #based on the information, calculate the average for technical_indicator to present the market average
    all_dataframe_list = []
    for i in range(df.index.unique()[-1] + 1):
        information = df[df.index == i]
        new_dataframe = []
        for tech in technical_indicator:
            tech_value = np.mean(information[tech])
            new_dataframe.append(tech_value)
        all_dataframe_list.append(new_dataframe)
    new_df = pd.DataFrame(all_dataframe_list, columns=technical_indicator)
    return new_df
make_market_information(test, ["zopen","zhigh", "zlow", "zadjcp", "zclose", "zd_5", "zd_10","zd_15", "zd_20", "zd_25", "zd_30"])

zopen     zhigh      zlow    zadjcp    zclose      zd_5     zd_10  \
0    -0.005008  0.005420 -0.012521 -0.212322  0.001038  0.001224 -0.009870   
1    -0.007300  0.005003 -0.015596 -0.212322  0.003440  0.001224 -0.009870   
2     0.001156  0.006943 -0.007975 -0.212043 -0.001199  0.001224 -0.009870   
3    -0.000333  0.005820 -0.008263 -0.212043  0.001803 -0.002500 -0.009870   
4     0.000571  0.007629 -0.007495 -0.212043  0.008054 -0.007629 -0.009870   
...        ...       ...       ...       ...       ...       ...       ...   
2006  0.001589  0.004278 -0.003463 -0.051178 -0.001137 -0.002803 -0.008433   
2007 -0.002547  0.002069 -0.005636 -0.051178  0.003603 -0.003561 -0.009250   
2008  0.000674  0.004389 -0.003894 -0.051178  0.001456 -0.003050 -0.008690   
2009  0.006716  0.009199 -0.003745 -0.051178 -0.006361  0.003072 -0.001060   
2010 -0.004321  0.001483 -0.007809 -0.051178  0.002872  0.000267 -0.002821   

         zd_15     zd_20     zd_25     zd_30  
0    -0.012237 -0.018594 -0.026002 -0.027599  
1    -0.012237 -0.018594 -0.026002 -0.027599  
2    -0.012237 -0.018594 -0.026002 -0.027599  
3    -0.012237 -0.018594 -0.026002 -0.027599  
4    -0.012237 -0.018594 -0.026002 -0.027599  
...        ...       ...       ...       ...  
2006 -0.014390 -0.016835 -0.018877 -0.020440  
2007 -0.015527 -0.019168 -0.021174 -0.022697  
2008 -0.014607 -0.019463 -0.021241 -0.023004  
2009 -0.006952 -0.012213 -0.013740 -0.015699  
2010 -0.008101 -0.013557 -0.015376 -0.017610  

[2011 rows x 11 columns]

In [2]:
import torch
a=torch.randn(2,2)
a

tensor([[ 0.3454,  2.8466],
        [-1.5950, -0.2258]])

In [3]:
a[0,-1]

tensor(2.8466)

In [2]:
torch.ones(20)==torch.ones(20)

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True])

In [4]:
torch.ones(20).equal(torch.ones(20))

True

In [2]:
technical_indicator=["zopen","zhigh", "zlow", "zadjcp", "zclose", "zd_5", "zd_10","zd_15", "zd_20", "zd_25", "zd_30"]

In [3]:
all_dataframe_list=[]
for i in range(test.index.unique()[-1]+1):
    information=test[test.index==i]
    new_dataframe=[]
    for tech in technical_indicator:
        tech_value=np.mean(information[tech])
        new_dataframe.append(tech_value)
    all_dataframe_list.append(new_dataframe)
new_df = pd.DataFrame(all_dataframe_list,columns=technical_indicator)    
        
new_df

zopen     zhigh      zlow    zadjcp    zclose      zd_5     zd_10  \
0    -0.005008  0.005420 -0.012521 -0.212322  0.001038  0.001224 -0.009870   
1    -0.007300  0.005003 -0.015596 -0.212322  0.003440  0.001224 -0.009870   
2     0.001156  0.006943 -0.007975 -0.212043 -0.001199  0.001224 -0.009870   
3    -0.000333  0.005820 -0.008263 -0.212043  0.001803 -0.002500 -0.009870   
4     0.000571  0.007629 -0.007495 -0.212043  0.008054 -0.007629 -0.009870   
...        ...       ...       ...       ...       ...       ...       ...   
2006  0.001589  0.004278 -0.003463 -0.051178 -0.001137 -0.002803 -0.008433   
2007 -0.002547  0.002069 -0.005636 -0.051178  0.003603 -0.003561 -0.009250   
2008  0.000674  0.004389 -0.003894 -0.051178  0.001456 -0.003050 -0.008690   
2009  0.006716  0.009199 -0.003745 -0.051178 -0.006361  0.003072 -0.001060   
2010 -0.004321  0.001483 -0.007809 -0.051178  0.002872  0.000267 -0.002821   

         zd_15     zd_20     zd_25     zd_30  
0    -0.012237 -0.018594 -0.026002 -0.027599  
1    -0.012237 -0.018594 -0.026002 -0.027599  
2    -0.012237 -0.018594 -0.026002 -0.027599  
3    -0.012237 -0.018594 -0.026002 -0.027599  
4    -0.012237 -0.018594 -0.026002 -0.027599  
...        ...       ...       ...       ...  
2006 -0.014390 -0.016835 -0.018877 -0.020440  
2007 -0.015527 -0.019168 -0.021174 -0.022697  
2008 -0.014607 -0.019463 -0.021241 -0.023004  
2009 -0.006952 -0.012213 -0.013740 -0.015699  
2010 -0.008101 -0.013557 -0.015376 -0.017610  

[2011 rows x 11 columns]

In [4]:
information=test[test.index==0]

In [5]:
np.mean(information["open"])

55.76500340165763

In [7]:
def correlation_coefficient_matrix():   
    # get symbols
    df = pd.read_csv("/home/sunshuo/qml/TradeMaster-1/data/data/dj30/train.csv",index_col=0)
 
    # sort symbols alphabetically
    df.sort_values(by='tic', ascending=True, inplace=True)
    array_symbols = df['tic'].values
     
    # get data, put into dictionary then dataframe
    dict_sym_ac = {}  # key=symbol, value=array of adj close
    for sym in array_symbols:
        dftemp = df[df['tic']==sym]
        dict_sym_ac[sym] = dftemp['adjcp'].values
     
    # create correlation coeff df
    dfdata = pd.DataFrame.from_dict(dict_sym_ac)
    dfcc = dfdata.corr().round(3)     
    return dfcc
df_corr=correlation_coefficient_matrix()
df_corr.shape

(29, 29)

In [8]:
A=df_corr.values
sum=np.sum(A,axis=1)

In [12]:
A/sum[1]

array([[ 1.08695652e+00, -3.36956522e-02,  9.78260870e-03,
        -1.08695652e-02,  2.17391304e-03,  3.26086957e-03,
         3.04347826e-02, -7.60869565e-03,  2.82608696e-02,
         1.41304348e-02, -5.43478261e-03,  1.52173913e-02,
         5.10869565e-02,  3.26086957e-02,  2.06521739e-02,
         9.78260870e-03,  4.34782609e-03,  2.39130435e-02,
         2.06521739e-02,  1.41304348e-02, -1.63043478e-02,
        -1.30434783e-02, -8.69565217e-03, -3.69565217e-02,
         2.82608696e-02, -2.60869565e-02,  2.39130435e-02,
        -1.30434783e-02, -1.19565217e-02],
       [-3.36956522e-02,  1.08695652e+00,  1.08695652e-03,
        -6.52173913e-03,  1.30434783e-02,  1.08695652e-02,
         2.60869565e-02,  5.54347826e-02, -1.08695652e-02,
         6.52173913e-03, -2.71739130e-02, -1.19565217e-02,
        -2.50000000e-02, -3.26086957e-03,  1.41304348e-02,
        -2.17391304e-02, -3.26086957e-03, -1.08695652e-02,
        -2.28260870e-02, -2.93478261e-02, -2.06521739e-02,
        -4.13

In [16]:
a=np.array([[1,2],[2,3]])

In [17]:
sum=np.sum(a,axis=1)

In [20]:
(a.T/sum).T

array([[0.33333333, 0.66666667],
       [0.4       , 0.6       ]])

In [19]:
sum

array([3, 5])

In [29]:
import torch
from torch import nn
corr_tensor=torch.from_numpy(df_corr.values/df_corr.values.sum(0)).to(torch.float)
H_L=torch.randn(12,29,10)
theta=torch.randn(10,10)
Z_l=torch.matmul(torch.matmul(corr_tensor,H_L),theta)

In [30]:
Z_l.shape

torch.Size([12, 29, 10])

In [33]:
torch.matmul(torch.randn(29,29),Z_l).transpose(1,2).shape

torch.Size([12, 10, 29])

In [36]:
(torch.matmul(torch.randn(29,29),Z_l).transpose(1,2)+H_L.transpose(1,2)).shape

torch.Size([12, 10, 29])

In [37]:
(torch.matmul(torch.randn(29,29),Z_l).transpose(1,2)+H_L.transpose(1,2)).transpose(0,2).reshape(29,-1).shape

torch.Size([29, 120])

In [38]:
linear_layer=nn.Linear(120,1)

In [39]:
(torch.matmul(torch.randn(29,29),Z_l).transpose(1,2)+H_L.transpose(1,2)).transpose(0,2).reshape(29,-1)

tensor([[-13.2055, -24.7030,  29.8546,  ...,  25.4757,  -1.3610,  19.2618],
        [  0.8493, -16.8559,  16.3238,  ...,  -4.8107,  -3.2931, -12.7132],
        [-40.8551,  17.8643,  -8.9494,  ...,  10.4244, -17.1789, -18.5953],
        ...,
        [ 25.7935,  54.3993,  -7.8799,  ...,   0.3189,  17.8442, -33.6028],
        [  3.2274,   0.0853, -23.1604,  ..., -37.0744,  34.7043,  24.7538],
        [ 27.0065,  22.3388,  -2.3154,  ...,  -8.6641,  13.4049,  -6.5285]])

In [41]:
v=torch.sigmoid(linear_layer((torch.matmul(torch.randn(29,29),Z_l).transpose(1,2)+H_L.transpose(1,2)).transpose(0,2).reshape(29,-1)))

tensor([[1.0000e+00],
        [3.2447e-01],
        [9.9969e-01],
        [1.4937e-04],
        [4.0361e-02],
        [7.7116e-06],
        [9.9732e-01],
        [1.0000e+00],
        [7.3402e-03],
        [2.7902e-03],
        [2.0375e-01],
        [1.5507e-07],
        [1.0000e+00],
        [1.0000e+00],
        [8.5462e-01],
        [3.1817e-03],
        [1.0604e-01],
        [1.0000e+00],
        [9.9931e-01],
        [1.3850e-02],
        [9.9925e-01],
        [1.0000e+00],
        [1.0000e+00],
        [1.3817e-12],
        [2.0878e-02],
        [1.0000e+00],
        [9.9998e-01],
        [2.6425e-04],
        [5.5056e-06]], grad_fn=<SigmoidBackward0>)

In [9]:
test[test["tic"]=="CRM"]

date        open        high         low       close       adjcp  \
0     2012-01-04   24.747499   24.875000   24.070000   24.370001   24.370001   
1     2012-01-05   24.235001   24.987499   23.790001   24.692499   24.692499   
2     2012-01-06   24.745001   25.312500   24.212500   25.264999   25.264999   
3     2012-01-09   25.205000   25.459999   24.882500   25.187500   25.187500   
4     2012-01-10   25.695000   26.202499   25.415001   26.197500   26.197500   
...          ...         ...         ...         ...         ...         ...   
2006  2019-12-24  163.309998  163.839996  162.880005  163.250000  163.250000   
2007  2019-12-26  163.399994  164.529999  163.270004  164.509995  164.509995   
2008  2019-12-27  164.860001  165.460007  163.899994  164.979996  164.979996   
2009  2019-12-30  164.860001  164.940002  161.199997  162.440002  162.440002   
2010  2019-12-31  162.039993  163.259995  161.800003  162.639999  162.639999   

      tic     zopen     zhigh      zlow  zadjcp    zclose      zd_5     zd_10  \
0     CRM  0.015490  0.020722 -0.012310     0.0 -0.036759 -0.000532 -0.014879   
1     CRM -0.018528  0.011947 -0.036549     0.0  0.013233 -0.000532 -0.014879   
2     CRM -0.020582  0.001880 -0.041658     0.0  0.023185 -0.000532 -0.014879   
3     CRM  0.000695  0.010819 -0.012109     0.0 -0.003067 -0.008913 -0.014879   
4     CRM -0.019181  0.000191 -0.029869     0.0  0.040099 -0.040271 -0.014879   
...   ...       ...       ...       ...     ...       ...       ...       ...   
2006  CRM  0.000368  0.003614 -0.002266     0.0 -0.002993  0.000123 -0.010077   
2007  CRM -0.006747  0.000122 -0.007537     0.0  0.007718 -0.003854 -0.012723   
2008  CRM -0.000727  0.002910 -0.006546     0.0  0.002857 -0.004691 -0.011662   
2009  CRM  0.014898  0.015390 -0.007634     0.0 -0.015396  0.008274  0.004599   
2010  CRM -0.003689  0.003812 -0.005165     0.0  0.001231  0.005681  0.003781   

         zd_15     zd_20     zd_25     zd_30  
0    -0.015927 -0.017220 -0.024889 -0.023492  
1    -0.015927 -0.017220 -0.024889 -0.023492  
2    -0.015927 -0.017220 -0.024889 -0.023492  
3    -0.015927 -0.017220 -0.024889 -0.023492  
4    -0.015927 -0.017220 -0.024889 -0.023492  
...        ...       ...       ...       ...  
2006 -0.018850 -0.016202 -0.013131 -0.011302  
2007 -0.023091 -0.023138 -0.020556 -0.018540  
2008 -0.023142 -0.024870 -0.023157 -0.020855  
2009 -0.006049 -0.009761 -0.007991 -0.005670  
2010 -0.005157 -0.010474 -0.009252 -0.007009  

[2011 rows x 18 columns]

In [10]:
df = pd.read_csv("/home/sunshuo/qml/TradeMaster-1/data/data/dj30/train.csv",index_col=0)
df.sort_values(by='tic', ascending=True, inplace=True)
array_symbols = df['tic'].values
     
    # get data, put into dictionary then dataframe
dict_sym_ac = {}  # key=symbol, value=array of adj close
for sym in array_symbols:
    dftemp = df[df['tic']==sym]
    dict_sym_ac[sym] = dftemp['adjcp'].values

In [11]:
dfdata = pd.DataFrame.from_dict(dict_sym_ac)

In [12]:
dfdata

AAPL      AMGN       AXP        BA       CAT  CRM      CSCO  \
0    -0.143726 -0.187244 -0.051417 -0.028303 -0.104209  0.0 -0.132201   
1    -0.033829 -0.117670 -0.044098 -0.028303 -0.164935  0.0 -0.259982   
2    -0.018836 -0.183331 -0.109180 -0.028303 -0.100052  0.0 -0.169409   
3    -0.143726 -0.084720 -0.133151 -0.162010 -0.215922  0.0 -0.176936   
4    -0.059916 -0.123660 -0.085752 -0.032770 -0.226766  0.0 -0.219536   
...        ...       ...       ...       ...       ...  ...       ...   
2006 -0.037206 -0.157928 -0.100902 -0.135686 -0.240687  0.0 -0.248984   
2007 -0.125335 -0.157928 -0.051418 -0.047007 -0.072696  0.0 -0.237587   
2008 -0.125336 -0.157929 -0.106526 -0.103167 -0.181719  0.0 -0.154915   
2009 -0.037206 -0.221163 -0.100902 -0.017811 -0.138010  0.0 -0.072619   
2010 -0.104143 -0.221163 -0.121507 -0.103167 -0.245507  0.0 -0.254500   

           CVX       DIS        GS  ...       MRK      MSFT       NKE  \
0    -0.184247 -0.079684 -0.077959  ... -0.085375 -0.144286 -0.019071   
1    -0.293476 -0.042380 -0.109496  ... -0.269111 -0.035001 -0.093919   
2    -0.241833 -0.049703 -0.151912  ... -0.269111 -0.169419 -0.021624   
3    -0.176611 -0.062566 -0.087050  ... -0.215297 -0.090437 -0.101301   
4    -0.224100 -0.062566 -0.072101  ... -0.163054 -0.150727 -0.034601   
...        ...       ...       ...  ...       ...       ...       ...   
2006 -0.136248 -0.012074 -0.149351  ... -0.103849 -0.156670 -0.079298   
2007 -0.316728 -0.056557 -0.092244  ... -0.109922 -0.181610 -0.076518   
2008 -0.153121 -0.090907 -0.099471  ... -0.209573 -0.150727 -0.052836   
2009 -0.322007 -0.035256 -0.077959  ... -0.262152 -0.078367 -0.082195   
2010 -0.127749 -0.104656 -0.120587  ... -0.150447 -0.061165 -0.066279   

            PG       TRV       UNH         V        VZ       WBA       WMT  
0    -0.108631 -0.085600 -0.048781 -0.043989 -0.261781 -0.238961 -0.159209  
1    -0.250122 -0.189502 -0.051811 -0.037107 -0.252191 -0.167679 -0.169739  
2    -0.226484 -0.111320 -0.048781 -0.016858 -0.227279 -0.163773 -0.076608  
3    -0.058441 -0.058924 -0.105815 -0.020078 -0.353570 -0.167679 -0.076608  
4    -0.148780 -0.160105 -0.109173 -0.016858 -0.242993 -0.171341 -0.035546  
...        ...       ...       ...       ...       ...       ...       ...  
2006 -0.190098 -0.080258 -0.079078 -0.026564 -0.294848 -0.130301 -0.153670  
2007 -0.076954 -0.140747 -0.054999 -0.054524 -0.227279 -0.197474 -0.189646  
2008 -0.195817 -0.080258 -0.144174 -0.047391 -0.369096 -0.222703 -0.039853  
2009 -0.262806 -0.058924 -0.054999 -0.054524 -0.200686 -0.174580 -0.148941  
2010 -0.243964 -0.210814 -0.045150 -0.061871 -0.200686 -0.193591 -0.035546  

[2011 rows x 29 columns]

In [15]:
dfdata.values.shape

(2011, 29)